---
- hosts: all
  #sudo apt install python3-tk
  vars:
   - pip_package: python3-pip
   - pip_executable: python3-pip
  
  roles:
    - { role: geerlingguy.pip, become: true }    
    - { role: fbaroni.findspark, become: true }