---
# tasks file for fbaroni.findspark

- name: Paquetes PIP | instala
  pip: name="{{ item }}" state=latest
  become: true
  with_items:
    - findspark
    - matplotlib
    - seaborn
    - pandas
    - jupyter
    - tweepy
    - textblob
  tags:
    - pip

